// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restoran.Entities;

#nullable disable

namespace Restoran.Migrations
{
    [DbContext(typeof(RestoranContext))]
    partial class RestoranContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restoran.Entities.Musterija", b =>
                {
                    b.Property<Guid>("MusterijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresaMusterije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradMusterije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeMusterije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktMusterije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeMusterije")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusterijaID");

                    b.ToTable("Musterija");
                });

            modelBuilder.Entity("Restoran.Entities.Porudzbina", b =>
                {
                    b.Property<Guid>("PorudzbinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DodeljeniSto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("IznosPorudzbine")
                        .HasColumnType("float");

                    b.Property<Guid>("MusterijaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NacinPlacanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusPorudzbine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ZaposleniID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PorudzbinaID");

                    b.ToTable("Porudzbina");
                });

            modelBuilder.Entity("Restoran.Entities.Proizvod", b =>
                {
                    b.Property<Guid>("ProizvodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Cena")
                        .HasColumnType("float");

                    b.Property<string>("Hrana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivProizvoda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProizvodID");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("Restoran.Entities.StavkaPorudzbine", b =>
                {
                    b.Property<Guid>("StavkaPorudzbineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<Guid>("PorudzbinaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProizvodID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StavkaPorudzbineID");

                    b.ToTable("StavkaPorudzbine");
                });

            modelBuilder.Entity("Restoran.Entities.Zaposleni", b =>
                {
                    b.Property<Guid>("ZaposleniID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdresaZaposlenog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradZaposlenog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeZaposlenog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktZaposlenog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeZaposlenog")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZaposleniID");

                    b.ToTable("Zaposleni");
                });
#pragma warning restore 612, 618
        }
    }
}
